version: '3.8'
services:
  app:
    container_name: sangiorgio_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: sangiorgio_mongodb
    image: mongo:4.2.24
    ports:
      - "27017:27017"
    env_file:
      - .env

volumes:
  sangiorgio_mongodb: